# Generated by Django 4.2.2 on 2023-06-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OPD_Reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=7)),
                ("addr", models.CharField(max_length=70)),
                ("ph_no", models.CharField(max_length=13)),
            ],
        ),
    ]
